# Generated by Django 4.2.6 on 2023-10-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
    ]
